name: Deploy Infrastructure and Run Scripts

on:
  push:
    branches:
      - main  # Or the branch you use for deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repo
    - name: Checkout GitHub repo
      uses: actions/checkout@v2
      
    # Log in to Azure
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy Bicep template for Infrastructure setup
    - name: Deploy Infrastructure with Bicep
      run: |
        az deployment sub create \
          --location ${{ secrets.AZURE_LOCATION }} \
          --template-file ./infrastructure/main.bicep \
          # Add parameters if needed using --parameters param1=value1 param2=value2
      
    # Find and run all shell scripts in the scripts directory
    - name: Run deployment scripts
      run: |
        chmod +x ./scripts/*.sh
        find ./scripts -type f -name "*.sh" -exec {} \;
